version: 2
project_name: sc

before:
  hooks:
    - go mod tidy
    - >-
      bash -c 'sed -n "/^## \[v{{.RawVersion}}\]/,/^## \[v/{/^## \[v{{.RawVersion}}\]/d;/^## \[v/d;p;}" CHANGELOG.md > /tmp/release-notes.md;
      if [ ! -s /tmp/release-notes.md ]; then echo "Release v{{.Version}}" > /tmp/release-notes.md; fi'

builds:
  - main: ./cmd/sc/
    binary: sc
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"

release:
  release_notes: /tmp/release-notes.md

changelog:
  disable: true
